gym/urls.py
from django.conf.urls import url
from views import (
    GymProfile, GymProfileUpdate, GymRegisterView, GymListView,
    photo_delete, photo_save, get_gym_list
)

urlpatterns = [
    url(r'list$', GymListView.as_view(), name='list'),
    url(r'json$', get_gym_list),
    url(r'detail/(?P<pk>[\d]+)/$', GymProfile.as_view(), name='detail'),
    url(r'settings/$', GymProfileUpdate.as_view(), name='settings'),
    url(r'register/$', GymRegisterView.as_view(), name='register'),  # ajax
    url(r'photo/save/$', photo_save, name='photo_save'),
    url(r'photo/delete/(?P<pk>[\d]+)/$', photo_delete, name='photo_delete'),
]

invite/urls.py
from django.conf.urls import url
from views import invite, submit, cancel

urlpatterns = [
    url(r'(?P<gym_pk>[\d]+)/(?P<trainer_pk>[\d]+)/(?P<ntype>[\d]+)$',
        invite, name='invite'),
    url(r'submit/(?P<pk>[\d]+)$', submit, name='submit'),
    url(r'cancel/(?P<pk>[\d]+)$', cancel, name='cancel'),
]

sport_katalog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from trainer.views import TrainerRegisterView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^allauth/', include('allauth.urls')),
    url(r'^', include('support.urls', namespace='support')),
    url(r'^trainer/', include('trainer.urls', namespace='trainer')),
    url(r'^gym/', include('gym.urls', namespace='gym')),
    url(r'^training_partner/', include('training_partner.urls', namespace='training_partner')),
    url(r'^invite/', include('invite.urls', namespace='invite')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^openhours/', include('openhours.urls', namespace='openhours')),
    url(r'^google64a2aa86f84ef7bf.html', TemplateView.as_view(template_name='google64a2aa86f84ef7bf.html')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/urls.py
from django.conf.urls import url
from views import (
    HomeView, get_cities, remove, 
    UserUpdateView, TariffSelectView
)
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^get_cities/', get_cities),
    url(r'^remove/(?P<gym_pk>[\d]+)/(?P<trainer_pk>[\d]+)', remove, name='remove'),
    url(r'^user/update/(?P<pk>[\d]+)', UserUpdateView.as_view(), name='user_update'),
    url(r'^tariff/select/', TariffSelectView.as_view(), name='tariff_select'),
]

trainer/urls.py
from django.conf.urls import url
from views import (
    TrainerProfile, TrainerProfileUpdate,
    photo_save, photo_delete, TrainerRegisterView
)

urlpatterns = [
    url(r'detail/(?P<pk>[\d]+)/$', TrainerProfile.as_view(), name='detail'),
    url(r'settings/$', TrainerProfileUpdate.as_view(), name='settings'),
    url(r'register/$', TrainerRegisterView.as_view(), name='register'),

    # ajax
    url(r'photo/save/$', photo_save, name='photo_save'),
    url(r'photo/delete/(?P<pk>[\d]+)/$', photo_delete, name='photo_delete'),
]

gym/models.py
from __future__ import unicode_literals
from django.contrib.gis.db import models
from trainer.models import Trainer
from django.contrib.auth.models import User
from cities.models import Country, City
from imagekit.models import ProcessedImageField


class Address(models.Model):
    country = models.ForeignKey(Country)
    city = models.ForeignKey(City)
    street = models.CharField(max_length=100)
    point = models.PointField(null=True)

    def __unicode__(self):
        return "%s, %s, %s" % (self.street, self.city, self.country)


class Gym(models.Model):
    name = models.CharField(max_length=100)
    address = models.ForeignKey('Address', related_name='gym_address')
    homepage_url = models.URLField(null=True)
    trainers = models.ManyToManyField(Trainer, related_name='gym_trainers')
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='gym')
    active = models.BooleanField(default=True)
    can_show = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.name


class GymPhoto(models.Model):
    gym = models.ForeignKey(Gym, related_name='photos')
    photo = ProcessedImageField(
        upload_to='gym/', format='JPEG', options={'quality': 60})
    avatar = models.BooleanField(default=False)

    def __unicode__(self):
        return self.gym.user.email

invite/models.py
from __future__ import unicode_literals

from django.db import models
from gym.models import Gym
from trainer.models import Trainer

NOTIFICATION_TYPES = (
    (0, 'trainer to gym'),
    (1, 'gym to trainer')
)


class Notification(models.Model):
    gym = models.ForeignKey(Gym)
    trainer = models.ForeignKey(Trainer)
    ntype = models.IntegerField(choices=NOTIFICATION_TYPES)

    def __unicode__(self):
        if self.ntype:
            return '%s to %s' % (self.gym.name, self.trainer.user.username)
        else:
            return '%s to %s' % (self.trainer.user.username, self.gym.name)

trainer/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from cities.models import Country, City
from phonenumber_field.modelfields import PhoneNumberField

from imagekit.models import ProcessedImageField


class Trainer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='trainer')
    first_name = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50)
    country = models.ForeignKey(Country)
    city = models.ForeignKey(City)
    phone = PhoneNumberField()
    certificate = models.CharField(max_length=50, null=True, blank=True)
    can_show = models.BooleanField(default=True)
    
    description = models.TextField(null=True, blank=True, verbose_name='About me')
    rate = models.FloatField(default=0.0)

    def __unicode__(self):
        return self.user.username


class TrainerPhoto(models.Model):
    trainer = models.ForeignKey(Trainer, related_name='photos')
    photo = ProcessedImageField(
        upload_to='client/', format='JPEG', options={'quality': 60})
    avatar = models.BooleanField(default=False)

    def __unicode__(self):
        return self.trainer.user.username

gym/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from models import Address, Gym
from support.functions import get_or_none
from support.forms import CityField
from cities.models import Country, City
from django.utils.translation import ugettext as _

class GymFilterForm(forms.Form):
    name = forms.CharField(
        max_length=30, 
        widget=forms.TextInput(attrs={'placeholder': _('Gym name')}), 
        required=False
    )
    country = forms.ModelChoiceField(
        queryset=Country.objects, 
        to_field_name='pk', empty_label=_('Country'),
        required=False
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.none(), 
        empty_label=_('Please, pick a country'),
        required=False
    )


class GymUpdateForm(forms.ModelForm):

    class Meta:
        model = Gym
        fields = ['name', 'homepage_url']


class AddressRegisterForm(forms.ModelForm):
    city = CityField(queryset=City.objects.none())

    class Meta:
        model = Address
        fields = '__all__'
        exclude = ['point']

trainer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from phonenumber_field.formfields import PhoneNumberField
from cities.models import Country, City

from support.forms import CityField
from models import Trainer

class TrainerRegisterForm(forms.ModelForm):
    city = CityField(queryset=City.objects.none())

    class Meta:
        model = Trainer
        fields = ['first_name', 'last_name',
                  'country', 'certificate', 'phone', 'city']

class TrainerAdminForm(forms.ModelForm):
    city = CityField(queryset=City.objects.none())

    class Meta:
        model = Trainer
        fields = '__all__'

class TrainerFilterForm(forms.Form):
    name = forms.CharField(
        max_length=30, 
        widget=forms.TextInput(attrs={'placeholder': _('Gym name')}),
        required=False
    )
    country = forms.ModelChoiceField(
        queryset=Country.objects, 
        to_field_name="pk", empty_label=_("Country"),
        required=False
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.none(), 
        empty_label=_("Please, pick a country"),
        required=False
    )

gym/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.contrib.gis.geos import Point
from django.utils.translation import ugettext as _
from django.template.loader import render_to_string
from django.forms import modelformset_factory
from datetime import datetime

from support.functions import get_or_none
from support.forms import UserProfileForm
from cities.models import Country, City
from models import Gym, Address, GymPhoto
from forms import (
    AddressRegisterForm, GymUpdateForm, GymFilterForm
)
from support.views import ListView
from invite.models import Notification
from openhours.models import OpenHours


def get_gym_list(request):
    if request.method == 'GET':
        gyms = Gym.objects.all()[:5]
    else:
        #ids = request.POST.getlist('ids[]')
        default_queryset = Gym.objects.all()
        fquery = Q()
        if request.POST.get('name', None):
            fquery = Q(name__icontains=request.POST['name'])
        if request.POST.get('country', None):
            fquery = fquery & Q(address__country=request.POST['country'])
        if request.POST.get('city', None):
            fquery = fquery & Q(address__city=request.POST['city'])
        gyms = default_queryset.filter(fquery)

    gyms_list = list()
    if gyms:
        for gym in gyms:
            if gym.address.point:
                avatar_photo = gym.photos.filter(avatar=True)
                temp = dict()
                temp['pk'] = gym.pk
                temp['name'] = gym.name
                temp['address'] = dict()
                temp['address']['coords'] = gym.address.point.coords
                temp['address']['country'] = gym.address.country.name
                temp['address']['city'] = gym.address.city.name
                temp['address']['street'] = gym.address.street
                temp['avatar'] = avatar_photo.get(
                ).photo.url if avatar_photo else "/static/image/not_found.png"
                gyms_list.append(temp)
        return JsonResponse({"data": gyms_list})
    return JsonResponse({"data": list()})


def gym_filter(get):
    default_queryset = Gym.objects.all()
    fquery = Q()
    if get.get('name', None):
        fquery = Q(name__icontains=get['name'])
    if get.get('country', None):
        fquery = fquery & Q(address__country=get['country'])
    if get.get('city', None):
        fquery = fquery & Q(address__city=get['city'])
    return default_queryset.filter(fquery)


class GymListView(TemplateView):
    template_name = 'gym/main.html'
    filter_form = GymFilterForm

    def get_context_data(self, request):
        context = dict()
        context['gym_list'] = gym_filter(request.GET)
        context['gym_list'] = ListView(Gym).get_list(
            request.GET, context['gym_list'])
        context['filter_form'] = self.filter_form()
        return context

    def get(self, request):
        context = self.get_context_data(request=request)
        return render(request, self.template_name, context)


class GymRegisterView(LoginRequiredMixin, CreateView):
    model = Gym
    form_address = AddressRegisterForm
    template_name = 'gym/register.html'
    fields = ['name', 'homepage_url']

    def get_context_data(self, **kwargs):
        context = super(GymRegisterView, self).get_context_data(**kwargs)
        context['address'] = self.form_address()
        return context

    def form_valid(self, form):
        address = self.form_address(self.request.POST)
        if address.is_valid():
            address = address.save()
            form.instance.address = address
            form.instance.user = self.request.user
        else:
            return self.form_invalid(form)
        return super(GymRegisterView, self).form_valid(form)

    def get_absolute_url(self):
        return reverse('gym:settings', args=(self.object.pk,))

class GymProfile(DetailView):
    template_name = 'gym/detail.html'
    model = Gym
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(GymProfile, self).get_context_data(**kwargs)
        user = self.request.user
        now = datetime.now()
        context['opened'] = self.object.openhours_set.filter(weekday=now.weekday() + 1, 
            from_hour__lte=now.strftime("%H:%M"),
            to_hour__gte=now.strftime("%H:%M")).exists()
        if user.is_authenticated() and not self.request.is_ajax():
            if (getattr(user, 'trainer', None) 
                and not get_or_none(Notification, gym=self.object, trainer=user.trainer, ntype=0) 
                and not user.trainer.gym_trainers.filter(pk=self.object.pk).exists()):
                context['invite'] = True
        return context

    def get(self, request, pk):
        if request.is_ajax():
            self.object = self.get_object()
            context = self.get_context_data(pk=pk)
            html = render_to_string('gym/content_detail.html', context)
            return HttpResponse(html)
        else:
            return super(GymProfile, self).get(request, pk)


class GymProfileUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'gym/settings.html'
    model = Gym
    fields = ['name', 'homepage_url']
    forms = {
        'form': GymUpdateForm,
        'address': AddressRegisterForm,
    }

    def get_context_data(self, **kwargs):
        context = super(GymProfileUpdate, self).get_context_data(**kwargs)
        context['address'] = self.forms['address'](
            instance=self.object.address)
        context['my_city'] = self.object.address.city
        context['cities'] = City.objects.filter(
            country=self.object.address.country)
        context['user_form'] = UserProfileForm(instance=self.request.user)

        hours = OpenHours.objects.filter(gym=self.request.user.gym)
        HoursFormset = modelformset_factory(OpenHours, exclude=['gym', 'id',], max_num=7, extra=7)
        context['hours_form'] = HoursFormset(queryset=hours)
        return context

    def get_object(self):
        return Gym.objects.get(user=self.request.user)

    def form_valid(self, form):
        from django.contrib.gis.geos import GEOSGeometry
        address = AddressRegisterForm(self.request.POST) 
        if address.is_valid():
            address = AddressRegisterForm(self.request.POST, instance=self.object.address)
            x, y = self.request.POST.get('point').split()
            print x, y
            address = address.save(commit=False)
            address.point =  GEOSGeometry('POINT(%s %s)' % (x, y))
            address.save()
            print address.point
        else:
            print address.errors
        form.save()
        return redirect('gym:settings')


@login_required
def photo_save(request):
    if request.user.gym.photos.count() >= 5:
        return HttpResponse(_('Max is 5'))
    avatar = get_or_none(GymPhoto, gym=request.user.gym, avatar=True)
    photo = GymPhoto(gym=request.user.gym, photo=request.FILES['file'])
    if not avatar:
        photo.avatar = True
    photo.save()
    return HttpResponse(_('Uploaded'))


@login_required
def photo_delete(request, pk):
    photo = get_or_none(GymPhoto, gym=request.user.gym, pk=pk)
    if photo:
        photo.delete()
        return HttpResponse(_('Deleted'))
    return HttpResponse(_('Photo does not exist'))


@login_required
def set_avatar(request, pk):
    photo = get_or_none(GymPhoto, gym=request.user.gym, pk=pk)
    old_avatar = get_or_none(GymPhoto, gym=request.user.gym, avatar=True)
    if old_avatar:
        old_avatar.avatar = False
        old_avatar.save()
    photo.avatar = True
    photo.save()
    return HttpResponse(_('Avatar set'))

production_static/templates/trainer/settings/details.html
{% load socialaccount %}
{% get_social_accounts object.user as accounts %}
{% load i18n %}

{% if accounts %}
<p>
<span class="ui small header">{% trans "Social accounts" %}:</span>
	{% if accounts.facebook %}
		<a href="{{ accounts.facebook.0.extra_data.link }}" target="_blank" class="ui tiny blue header">Facebook</a>
	{% else %}
		<a href="{% provider_login_url "facebook" method="oauth2" process="connect" %}&next={% url "trainer:settings" %}">
		Facebook
		<i class="mini add icon"></i>
		</a>
	{% endif %}
	{% if accounts.google %}
		<span class="ui tiny blue header">Google</span>
	{% else %}
		<a href="{% provider_login_url "google" method="oauth2" process="connect" %}&next={% url "trainer:settings" %}">
			Google
			<i class="mini green add icon"></i>
		</a>
	{% endif %}
</p>
{% endif %}
<form action="" method="post" class="ui form">
	{% csrf_token %}
	<div class="two fields">
		<div class="field">
			<label>{{ form.first_name.label }}:</label>
			{{ form.first_name }}
		</div>
		<div class="field">
			<label>{{ form.last_name.label }}:</label>
			{{ form.last_name }}
		</div>
	</div>
	<div class="two fields">
		<div class="field">
			<label>{{ form.phone.label }}</label>
			{{ form.phone }}
		</div>
		<div class="field">
			<label>{{ form.certificate.label }}</label>
			{{ form.certificate }}
		</div>
	</div>
	<div class="two fields">
		<div class="field">
			<label>{{ form.country.label }}</label>
			{{ form.country }}
		</div>
		<div class="field">
			<label for="id_city">City:</label>
			<select id="id_city" name="city">
				<option value="{{ my_city.id }}" selected>{{ my_city.name_std }}</option>
			</select>
		</div>	
	</div>
	<div class="fields">
		<div class="field">
			<button class="ui blue button" name="update">{% trans "Update" %}</button>
		</div>
		<div class="field">
			<button class="ui orange button" name="cancel">{% trans "Cancel" %}</button>
		</div>
	</div>
</form>

production_static/templates/trainer/settings/gyms.html
{% load i18n %}

{% if object.gym_trainers.all %}
<table class="ui table">
	<thead>
		<tr>
			<th class="eight wide">{% trans "Gym" %}</th>
			<th class="eight wide">{% trans "Delete" %}</th>
		</tr>
	</thead>
	<tbody>
		{% for gym in object.gym_trainers.all %}
		<tr>
			<td><a href="{% url "gym:detail" gym.pk %}">{{ gym }}</a></td>
			<td>
				<a class="refresh" href="{% url "support:remove" gym.pk object.pk %}">
					<i class="large red remove icon"></i>
				</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% else %}
	<h3 class="ui header">
		{% trans "You don't have any gyms, where you are working." %}
	</h3>
	<h5 class="ui header">
		{% url "gym:list" as gym_list_url %}
		{% blocktrans %} 
			Advise: You can find they <a href="{{ gym_list_url }}" class="ui green">here</a>
		{% endblocktrans %}
	</h5>
{% endif %}
{% if object.notification_set.all %}
<h3 class="ui green header">{% trans "New invites" %}</h3>
<table class="ui table">
	<thead>
		<tr>
			<th class="eight wide">{% trans "From" %}</th>
			<th class="eight wide">{% trans "Submit" %}</th>
			<th class="eight wide">{% trans "Cancel" %}</th>
		</tr>
	</thead>
	<tbody>
		{% for invite in invites %}
		<tr>
			<td><a href="{% url "gym:detail" invite.gym.pk %}">{{ invite.gym }}</a></td>
			<td>
				<a href="{% url "invite:submit" invite.pk %}" class="refresh">
					<i class="large green checkmark icon"></i>
				</a>
			</td>
			<td>
				<a href="{% url "invite:cancel" invite.pk %}" class="refresh">
					<i class="large red remove icon"></i>
				</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% else %}
<h3 class="ui green header">{% trans "You don't have any new invites" %}</h3>
{% endif %}

production_static/templates/trainer/settings/photos.html
{% load i18n %}

<h4 class="ui centered header">{% trans "Max 5 photos." %}</h4>
<div class="ui small images">
	{% for photo in object.photos.all %}
		<div class="ui image">
			<div class="moon-image">
				<a class="ui tiny right corner label" href="">
					<i class="remove icon"></i>
				</a>
				{% if photo.avatar %}
				<a class="ui tiny green left corner label" href="">
					<i class="user icon"></i>
				</a>
				{% else %}
				<a class="ui tiny left corner label" href="">
					<i class="user icon"></i>
				</a>
				{% endif %}
				<img src="{{ photo.photo.url }}">
			</div>
		</div>
	{% endfor %}
</div>
<form action="{% url "trainer:photo_save" %}" method="post" class="dropzone" enctype="multipart/form-data">
	{% csrf_token %}
</form>