gym/urls.py
from django.conf.urls import url
from views import (
    GymProfile, GymProfileUpdate, GymRegisterView, GymListView,
    photo_delete, photo_save, get_gym_list
)

urlpatterns = [
    url(r'list$', GymListView.as_view(), name='list'),
    url(r'json$', get_gym_list),
    url(r'detail/(?P<pk>[\d]+)/$', GymProfile.as_view(), name='detail'),
    url(r'settings/$', GymProfileUpdate.as_view(), name='settings'),
    url(r'register/$', GymRegisterView.as_view(), name='register'),  # ajax
    url(r'photo/save/$', photo_save, name='photo_save'),
    url(r'photo/delete/(?P<pk>[\d]+)/$', photo_delete, name='photo_delete'),
]

sport_katalog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from trainer.views import TrainerRegisterView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^allauth/', include('allauth.urls')),
    url(r'^', include('support.urls', namespace='support')),
    url(r'^trainer/', include('trainer.urls', namespace='trainer')),
    url(r'^gym/', include('gym.urls', namespace='gym')),
    url(r'^training_partner/', include('training_partner.urls', namespace='training_partner')),
    url(r'^invite/', include('invite.urls', namespace='invite')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^openhours/', include('openhours.urls', namespace='openhours')),
    url(r'^google64a2aa86f84ef7bf.html', TemplateView.as_view(template_name='google64a2aa86f84ef7bf.html')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

training_partner/urls.py
from django.conf.urls import url
from views import (
    TrainingPartnerProfile, TrainingPartnerView, TrainingPartnerRegisterView
)

urlpatterns = [
    url(r'list$', TrainingPartnerView.as_view(), name='list'),
    url(r'register$', TrainingPartnerRegisterView.as_view(), name='register'),
    url(r'detail/(?P<pk>[\d]+)/$', TrainingPartnerProfile.as_view(), name='detail'),
]

training_partner/models.py
from __future__ import unicode_literals

from django.db import models
from cities.models import Country, City
from phonenumber_field.modelfields import PhoneNumberField


class TrainingPartner(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    country = models.ForeignKey(Country, null=True, blank=True)
    city = models.ForeignKey(City, null=True, blank=True)
    phone = PhoneNumberField(null=True, blank=True)
    description = models.TextField()
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.CharField(max_length=50)

    def __unicode__(self):
        return self.last_name + " " + self.first_name

    class Meta:
        ordering = ['created']

training_partner/forms.py
from django import forms
from models import TrainingPartner
from cities.models import Country, City
from support.functions import get_or_none


class CityField(forms.ChoiceField):
    def validate(self, value):
        if get_or_none(City, pk=value):
            return
        raise forms.ValidationError(_('City is required'))


class TrainingPartnerForm(forms.ModelForm):
    city = CityField(choices=())

    class Meta:
        model = TrainingPartner
        # fields = ['first_name', 'last_name', 'description', 'email', 'phone', 'country', 'city']
        fields = '__all__'
        exclude = ['city']


class TrainingPartnerFilterForm(forms.Form):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'placeholder': 'Partner name'}
                               )
    )
    country = forms.ModelChoiceField(
        queryset=Country.objects, to_field_name="pk", empty_label="Country")
    city = forms.ModelChoiceField(
        queryset=City.objects.none(), empty_label="Please, pick a country")

training_partner/views.py
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from training_partner.forms import (TrainingPartnerForm,
                                    TrainingPartnerFilterForm)
from models import TrainingPartner
from django.db.models import Q
from support.views import ListView
from django.template.loader import render_to_string
from django.template import RequestContext
from django.http import HttpResponse
from support.functions import get_or_none


def trainer_partner_filter(get):
    default_queryset = TrainingPartner.objects.all()
    fquery = Q()
    if get.get('name', None):
        fquery = Q(first_name__icontains=get['name'])
        fquery = fquery | Q(last_name__icontains=get['name'])
    if get.get('country', None):
        fquery = fquery & Q(country=get['country'])
    if get.get('city', None):
        fquery = fquery & Q(city=get['city'])
    return default_queryset.filter(fquery)


class TrainingPartnerView(DetailView):
    """docstring for TrainingPartnerView"""
    training_partner_form = TrainingPartnerForm
    filter_form = TrainingPartnerFilterForm
    template_name = 'training_partner/main.html'

    def get(self, request):
        context = self.get_context_data(request=request)
        return render(request, self.template_name, context)

    def get_context_data(self, request):
        context = dict()
        context['register_form'] = self.training_partner_form()
        context['trainer_partner_list'] = trainer_partner_filter(request.GET)
        context['trainer_partner_list'] = ListView(TrainingPartner).get_list(
            request.GET, context['trainer_partner_list'])
        context['filter_form'] = self.filter_form()

        return context

    def post(self, request):
        training_form = self.training_partner_form(request.POST)
        if training_form.is_valid():
            training_form.save()
            return redirect('training_partner:list')
        context = self.get_context_data(request)
        return render(request, self.template_name, context)


class TrainingPartnerProfile(DetailView):
    template_name = 'training_partner/detail.html'
    model = TrainingPartner
    fields = '__all__'

    def get(self, request, pk):
        if request.is_ajax():
            self.object = self.get_object()
            context = self.get_context_data(pk=pk)
            html = render_to_string('training_partner/content_detail.html', context)
            return HttpResponse(html)

class TrainingPartnerRegisterView(DetailView):
    register_form = TrainingPartnerForm
    template_name = 'training_partner/register_content.html'
    fields = '__all__'
    model = TrainingPartner

    def get_context_data(self):
        context = dict()
        context['register_form'] = self.register_form()
        return context

    def get(self, request):
        context = self.get_context_data()
        # html = render_to_string('training_partner/register_content.html', context, context_instance=RequestContext(request))
        return render(request, 'training_partner/register_content.html', context)


# class TrainingPartnerRegisterView(TemplateView):
#     forms = {
#         'form': TrainingPartnerForm
#     }
#     template_name = 'training_partner/register_content.html'

#     def get_context_data(self, **kwargs):
#         context = super(TrainingPartnerRegisterView, self).get_context_data(**kwargs)
#         for name, form in self.forms.iteritems():
#             if self.request.POST:
#                 context[name] = form(self.request.POST)
#             else:
#                 context[name] = form()
#         return context

#     def post(self, request):
#         context = self.get_context_data()
#         errors = False
#         for name, form in self.forms.iteritems():
#             context[name] = form(request.POST)
#             if not context[name].is_valid():
#                 errors = True
#         if errors:
#             return render(request, self.template_name, context)
#         else:
#             training_partner_form = context['form']
#             training = TrainingPartner(
#                 email=gym_form.cleaned_data['email'],
#                 description=gym_form.cleaned_data['description'],
#                 first_name=gym_form.cleaned_data['first_name'],
#                 last_name=gym_form.cleaned_data['last_name'],
#                 last_name=gym_form.cleaned_data['last_name'],
#             )
#             user.save()
#             point = request.POST.get('point').split()
#             address = Address(
#                 country=address_form.cleaned_data['country'],
#                 city=get_or_none(City, pk=address_form.cleaned_data['city']),
#                 street=address_form.cleaned_data['street'],
#                 number=address_form.cleaned_data['number'],
#                 postcode=address_form.cleaned_data['postcode'],
#                 point=Point(float(point[0]), float(point[1]))
#             )
#             address.save()
#             gym = Gym(
#                 name=gym_form.cleaned_data['name'],
#                 user=user,
#                 address=address
#             ).save()
#         return redirect('accounts:auth_login')

production_static/templates/training_partner/content_detail.html
<div class="center aligned row">
	<div class="column">
		<p><h4 class="ui header">{{ object.first_name }} {{ object.last_name }}</h4></p>
		<p><h5 class="ui header">{{ object.email }}</h5></p>
		{% if object.phone %}
			<p><h5 class="ui header">{{ object.phone }}</h5></p>
		{% endif %}
		<p><h5 class="ui header">{{ object.country }}, {{ object.city }}</h5></p>
		<p>{{ object.description }}</p>
	</div>
</div>

production_static/templates/training_partner/main.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="sixteen wide column">
			<form action="" method="get" class="ui form">
				<div class="fields">
					{% csrf_token %}
					{% for field in filter_form %}
						<div class="four wide field">
							<!-- <label>{{ field.label }}</label> -->
							{{ field }}
						</div>
					{% endfor %}
					<div class="four wide field">
						<button class="ui blue button" name="filter">Filter</button>
					</div>
					<div class="four wide field">
						<a href="{% url "training_partner:register" %}" class="ui green button" name="add" id="modal-register-proposal-btn">Add Proposal</a>
						<div class="ui modal modal-register-proposal-show" id="modal-register-proposal">
							<div class="ui grid">
								<div class="center aligned row">
									<div class="column">
										<p><h4 class="ui header">Add new proposal</h4></p>
										<form action="" method="post" class="ui form">
											{% csrf_token %}
											<div class="field {% if register_form.first_name.errors %} error {% endif %}">
												<label>First Name:</label>
												{{ register_form.first_name }}
											</div>
											<div class="field {% if register_form.last_name.errors %} error {% endif %}">
												<label>Last Name:</label>
												{{ register_form.last_name }}
											</div>
											<div class="field {% if register_form.email.errors %} error {% endif %}">
												<label>{{ register_form.email.label }}:</label>
												{{ register_form.email }}
											</div>
											<div class="field {% if register_form.description.errors %} error {% endif %}">
												<label>{{ register_form.description.label }}:</label>
												{{ register_form.description }}
											</div>
											<div class="two fields">
												<div class="field {% if register_form.country.errors %} error {% endif %}">
													<label>County:</label>
													{{ register_form.country }}
												</div>
												<div class="field {% if register_form.city.errors %} error {% endif %}">
													<label>City:</label>
													{{ register_form.city }}
												</div>
											</div>
											<div class="field">
												<button type="submit" class="ui blue button" name="register">Add</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="row">
	<div class="fourteen wide column">
			{% include "training_partner/partner_list.html" %}
	</div>
{% endblock %}

production_static/templates/training_partner/partner_list.html
{% load help_tags %}
{% load staticfiles %}
{% if trainer_partner_list %}
<div class="ui items">
	{% for object in trainer_partner_list.objects %}
	<div class="ui card">
		<div class="content">
		  	<div class="header">{{ object.first_name }} {{ object.last_name}}</div>
		  	<div class="meta">{{ object.country }} {{ object.city }}<span style="float:right">{{ object.created }}</span></div>
		    <div class="description">
		      <p>{{ object.description|cut:140 }}</p>
		    </div>
	    </div>
		<a href="{% url "training_partner:detail" object.pk %}" class="ui bottom attached button modal-training-partner" 
					modal-id="training_partner-{{ object.pk }}" training-partner-id="{{ object.pk }}">
	      	Open
	    </a>
	    <div class="ui modal modal-training-show" id="training_partner-{{ object.pk }}">
			<div class="ui grid">
				<div class="center aligned row">
					<div class="column">
						<p><h4 class="ui header">Add new proposal</h4></p>
						<form action="" method="post" class="ui form">
							{% csrf_token %}
							<div class="field {% if register_form.first_name.errors %} error {% endif %}">
								<label>First Name:</label>
								{{ register_form.first_name }}
							</div>
							<div class="field {% if register_form.last_name.errors %} error {% endif %}">
								<label>Last Name:</label>
								{{ register_form.last_name }}
							</div>
							<div class="field {% if register_form.email.errors %} error {% endif %}">
								<label>{{ register_form.email.label }}:</label>
								{{ register_form.email }}
							</div>
							<div class="field {% if register_form.description.errors %} error {% endif %}">
								<label>{{ register_form.description.label }}:</label>
								{{ register_form.description }}
							</div>
							<div class="two fields">
								<div class="field {% if register_form.country.errors %} error {% endif %}">
									<label>County:</label>
									{{ register_form.country }}
								</div>
								<div class="field {% if register_form.city.errors %} error {% endif %}">
									<label>City:</label>
									{{ register_form.city }}
								</div>
							</div>
							<div class="field">
								<button type="submit" class="ui blue button" name="register">Add</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% if list.objects.has_other_pages %}
<div class="ui pagination menu">
	{% if trainer_partner_list.objects.has_previous %}
	<a class="icon item" href="?page={{ table.objects.previous_page_number }}">
		<i class="left chevron icon"></i>
	</a>
	{% endif %}
	{% comment %}
	{% for page in trainer_partner_list.objects.paginator.num_pages|trange %}
	<a class="item" href="?page={{ page }}">{{ page }}</a>
	{% endfor %}
	{% endcomment %}
	{% if trainer_partner_list.objects.has_next %}
	<a class="icon item" href="?page={{ table.objects.next_page_number }}">
		<i class="right chevron icon" ></i>
	</a>
	{% endif %}
</div>
{% endif %}
{% else %}
<h5>No object found</h5>
{% endif %}

production_static/templates/training_partner/register_content.html
<div class="center aligned row">
	<div class="column">
		<p><h4 class="ui header">Add new proposal</h4></p>
		<form action="" method="post" class="ui form">
			{% csrf_token %}
			<div class="field {% if register_form.first_name.errors %} error {% endif %}">
				<label>First Name:</label>
				{{ register_form.first_name }}
			</div>
			<div class="field {% if register_form.last_name.errors %} error {% endif %}">
				<label>Last Name:</label>
				{{ register_form.last_name }}
			</div>
			<div class="field {% if register_form.email.errors %} error {% endif %}">
				<label>{{ register_form.email.label }}:</label>
				{{ register_form.email }}
			</div>
			<div class="field {% if register_form.description.errors %} error {% endif %}">
				<label>{{ register_form.description.label }}:</label>
				{{ register_form.description }}
			</div>
			<div class="two fields">
				<div class="field {% if register_form.country.errors %} error {% endif %}">
					<label>County:</label>
					{{ register_form.country }}
				</div>
				<div class="field {% if register_form.city.errors %} error {% endif %}">
					<label>City:</label>
					{{ register_form.city }}
				</div>
			</div>
			<div class="field">
				<button type="submit" class="ui blue button" name="register">Add</button>
			</div>
		</form>
	</div>
</div>