gym/urls.py
from django.conf.urls import url
from views import (
    GymProfile, GymProfileUpdate, GymRegisterView, GymListView,
    photo_delete, photo_save, get_gym_list
)

urlpatterns = [
    url(r'list$', GymListView.as_view(), name='list'),
    url(r'json$', get_gym_list),
    url(r'detail/(?P<pk>[\d]+)/$', GymProfile.as_view(), name='detail'),
    url(r'settings/$', GymProfileUpdate.as_view(), name='settings'),
    url(r'register/$', GymRegisterView.as_view(), name='register'),  # ajax
    url(r'photo/save/$', photo_save, name='photo_save'),
    url(r'photo/delete/(?P<pk>[\d]+)/$', photo_delete, name='photo_delete'),
]

message/urls.py
from django.conf.urls import url
from views import ShowMessagesView, SendMessageView 

urlpatterns = [
    url(r'show$', ShowMessagesView.as_view(), name='show'),
    url(r'send/(?P<pk>[\d]+)/$', SendMessageView.as_view(), name='send'),
]

sport_katalog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from trainer.views import TrainerRegisterView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^allauth/', include('allauth.urls')),
    url(r'^', include('support.urls', namespace='support')),
    url(r'^trainer/', include('trainer.urls', namespace='trainer')),
    url(r'^gym/', include('gym.urls', namespace='gym')),
    url(r'^training_partner/', include('training_partner.urls', namespace='training_partner')),
    url(r'^invite/', include('invite.urls', namespace='invite')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^openhours/', include('openhours.urls', namespace='openhours')),
    url(r'^google64a2aa86f84ef7bf.html', TemplateView.as_view(template_name='google64a2aa86f84ef7bf.html')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/urls.py
from django.conf.urls import url
from views import (
    HomeView, get_cities, remove, 
    UserUpdateView, TariffSelectView
)
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^get_cities/', get_cities),
    url(r'^remove/(?P<gym_pk>[\d]+)/(?P<trainer_pk>[\d]+)', remove, name='remove'),
    url(r'^user/update/(?P<pk>[\d]+)', UserUpdateView.as_view(), name='user_update'),
    url(r'^tariff/select/', TariffSelectView.as_view(), name='tariff_select'),
]

production_static/templates/base.html
{% load staticfiles %}
{% load help_tags %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>MyTrainer</title>
    <link rel="stylesheet" type="text/css" href="{% static "semantic/semantic.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/dropzone.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/fotorama.css" %}">
    <script type="text/javascript" src="{% static "js/jquery-1.12.2.js" %}"></script>
</head>
<body>
    <div class="ui grid">
        <div class="row top-menu">
            <div class="column">
                <div class="ui {% if request.user.is_anonymous %} four {% else %} three {% endif %} item menu">
                    <a href="{% url "support:home" %}" class="item">{% trans "Trainers" %}</a>
                    <a href="{% url "gym:list" %}" class="item">{% trans "Gyms" %}</a>
                    <a href="{% url "training_partner:list" %}" class="item">Training Partners</a>
                    {% if request.user.is_anonymous %}
                    <a href="{% url "account_signup" %}" class="item">{% trans "Register" %}</a>
                    <a href="{% url "account_login" %}" class="item">{% trans "Login" %}</a>
                    {% else %}
                    <div class="ui pointing dropdown item">
                        <div class="text">{% trans "Me" %}</div>
                        <i class="dropdown icon"></i>
                        <div class="menu">
                        {% if request.user.gym %}
                            <a href="{% url "gym:detail" request.user.gym.id %}" class="item">{% trans "Profile" %}</a>
                            <a href="{% url "message:show" %}" class="item">{% trans "Messages" %}</a>
                            <a href="{% url "gym:settings" %}" class="item">{% trans "Settings" %}</a>
                        {% elif request.user.trainer %}
                            <a href="{% url "trainer:detail" request.user.trainer.id %}" class="item">{% trans "Profile" %}</a>
                            <a href="{% url "message:show" %}" class="item">{% trans "Messages" %}</a>
                            <a href="{% url "trainer:settings" %}" class="item">{% trans "Settings" %}</a>
                        {% else %}
                            <a href="{% url "trainer:register" %}" class="item">{% trans "Trainer" %}</a>
                            <a href="{% url "gym:register" %}" class="item">{% trans "Gym" %}</a>
                        {% endif %}
                            <div class="ui divider"></div>
                            <a href="{% url "account_logout" %}" class="item">{% trans "Logout" %}</a>
                        </div>
                    </div>                  
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="ui grid container">
        <div class="row">
            <div class="column">
                {% get_available_languages as languages %}
                    {% for lang_code, lang_name in languages %}
                        <a class="change_lang" rel="alternate" hreflang="{{ lang_code }}" href="{% change_lang lang_code %}"> 
                            {{ lang_name }} 
                        </a>
                    {% endfor %}
            </div>
        </div>
        {% block content %}
        {% endblock %}
        </div>
    </div>
    <script type="text/javascript" src="{% static "semantic/semantic.js" %}"></script>
    <script type="text/javascript" src="{% static "js/main.js" %}"></script>
    <script type="text/javascript" src="{% static "js/cities.js" %}"></script>
    <script type="text/javascript" src="{% static "js/dropzone.js" %}"></script>
    <script type="text/javascript" src="{% static "js/address.js" %}"></script>
    <script type="text/javascript" src="{% static "js/fotorama.js" %}"></script>
    <script type="text/javascript">
        if (window.location.hash && window.location.hash == '#_=_') {
            history.pushState("", document.title, window.location.pathname);
        }
    </script>
</body>
</html>

production_static/templates/google64a2aa86f84ef7bf.html
google-site-verification: google64a2aa86f84ef7bf.html