gym/urls.py
from django.conf.urls import url
from views import (
    GymProfile, GymProfileUpdate, GymRegisterView, GymListView,
    photo_delete, photo_save, get_gym_list
)

urlpatterns = [
    url(r'list$', GymListView.as_view(), name='list'),
    url(r'json$', get_gym_list),
    url(r'detail/(?P<pk>[\d]+)/$', GymProfile.as_view(), name='detail'),
    url(r'settings/$', GymProfileUpdate.as_view(), name='settings'),
    url(r'register/$', GymRegisterView.as_view(), name='register'),  # ajax
    url(r'photo/save/$', photo_save, name='photo_save'),
    url(r'photo/delete/(?P<pk>[\d]+)/$', photo_delete, name='photo_delete'),
]

invite/urls.py
from django.conf.urls import url
from views import invite, submit, cancel

urlpatterns = [
    url(r'(?P<gym_pk>[\d]+)/(?P<trainer_pk>[\d]+)/(?P<ntype>[\d]+)$',
        invite, name='invite'),
    url(r'submit/(?P<pk>[\d]+)$', submit, name='submit'),
    url(r'cancel/(?P<pk>[\d]+)$', cancel, name='cancel'),
]

sport_katalog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from trainer.views import TrainerRegisterView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^allauth/', include('allauth.urls')),
    url(r'^', include('support.urls', namespace='support')),
    url(r'^trainer/', include('trainer.urls', namespace='trainer')),
    url(r'^gym/', include('gym.urls', namespace='gym')),
    url(r'^training_partner/', include('training_partner.urls', namespace='training_partner')),
    url(r'^invite/', include('invite.urls', namespace='invite')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^openhours/', include('openhours.urls', namespace='openhours')),
    url(r'^google64a2aa86f84ef7bf.html', TemplateView.as_view(template_name='google64a2aa86f84ef7bf.html')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainer/urls.py
from django.conf.urls import url
from views import (
    TrainerProfile, TrainerProfileUpdate,
    photo_save, photo_delete, TrainerRegisterView
)

urlpatterns = [
    url(r'detail/(?P<pk>[\d]+)/$', TrainerProfile.as_view(), name='detail'),
    url(r'settings/$', TrainerProfileUpdate.as_view(), name='settings'),
    url(r'register/$', TrainerRegisterView.as_view(), name='register'),

    # ajax
    url(r'photo/save/$', photo_save, name='photo_save'),
    url(r'photo/delete/(?P<pk>[\d]+)/$', photo_delete, name='photo_delete'),
]

trainer/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from cities.models import Country, City
from phonenumber_field.modelfields import PhoneNumberField

from imagekit.models import ProcessedImageField


class Trainer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='trainer')
    first_name = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50)
    country = models.ForeignKey(Country)
    city = models.ForeignKey(City)
    phone = PhoneNumberField()
    certificate = models.CharField(max_length=50, null=True, blank=True)
    can_show = models.BooleanField(default=True)
    
    description = models.TextField(null=True, blank=True, verbose_name='About me')
    rate = models.FloatField(default=0.0)

    def __unicode__(self):
        return self.user.username


class TrainerPhoto(models.Model):
    trainer = models.ForeignKey(Trainer, related_name='photos')
    photo = ProcessedImageField(
        upload_to='client/', format='JPEG', options={'quality': 60})
    avatar = models.BooleanField(default=False)

    def __unicode__(self):
        return self.trainer.user.username

trainer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from phonenumber_field.formfields import PhoneNumberField
from cities.models import Country, City

from support.forms import CityField
from models import Trainer

class TrainerRegisterForm(forms.ModelForm):
    city = CityField(queryset=City.objects.none())

    class Meta:
        model = Trainer
        fields = ['first_name', 'last_name',
                  'country', 'certificate', 'phone', 'city']

class TrainerAdminForm(forms.ModelForm):
    city = CityField(queryset=City.objects.none())

    class Meta:
        model = Trainer
        fields = '__all__'

class TrainerFilterForm(forms.Form):
    name = forms.CharField(
        max_length=30, 
        widget=forms.TextInput(attrs={'placeholder': _('Gym name')}),
        required=False
    )
    country = forms.ModelChoiceField(
        queryset=Country.objects, 
        to_field_name="pk", empty_label=_("Country"),
        required=False
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.none(), 
        empty_label=_("Please, pick a country"),
        required=False
    )

trainer/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.translation import ugettext as _

from support.forms import UserProfileForm
from forms import TrainerRegisterForm
from cities.models import City, Country
from models import Trainer, TrainerPhoto
from support.functions import get_or_none
from review.forms import ReviewForm
from invite.models import Notification
from gym.models import Gym
from message.forms import MessageCreateForm


class TrainerRegisterView(LoginRequiredMixin, CreateView):
    template_name = 'trainer/register.html'
    model = Trainer
    form_class = TrainerRegisterForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TrainerRegisterView, self).form_valid(form)

    def get_success_url(self):
        return reverse('trainer:settings')


class TrainerProfile(DetailView):
    model = Trainer
    template_name = 'trainer/detail.html'
    review_form = ReviewForm
    message_form = MessageCreateForm

    def get_context_data(self, **kwargs):
        context = super(TrainerProfile, self).get_context_data(**kwargs)
        context['review_form'] = self.review_form()
        context['message_form'] = self.message_form()
        try:
            context['rating'] = sum(self.object.reviews.values_list(
                'rate', flat=True)) / self.object.reviews.count()
        except ZeroDivisionError:
            context['rating'] = 0
        user = self.request.user
        if user.is_authenticated():
            if (getattr(user, 'gym', None) 
                and not get_or_none(Notification, gym=user.gym, trainer=self.object, ntype=1) 
                and not user.gym.trainers.filter(pk=self.object.pk).exists()):
                context['invite'] = True
        return context

    def post(self, request, pk):
        self.object = self.get_object()
        context = self.get_context_data(pk=pk)
        review_form = self.review_form(request.POST)
        context['review_form'] = review_form
        if review_form.is_valid():
            rate_sum = float(sum(self.object.reviews.values_list(
                'rate', flat=True)) + review_form.cleaned_data['rate'])

            print rate_sum
            self.object.rate = (((self.object.reviews.count(
            ) + 1) / (6 - rate_sum / (self.object.reviews.count() + 1))))
            print self.object.rate
            self.object.save()
            review = review_form.save(commit=False)
            review.trainer = self.object
            review.save()
            return redirect('trainer:detail', pk=pk)
        return render(request, self.template_name, context)


class TrainerProfileUpdate(LoginRequiredMixin, UpdateView):
    login_url = 'account_login'
    model = Trainer
    template_name = 'trainer/settings.html'
    form_class = TrainerRegisterForm
    success_url = 'trainer:settings'
    user_form = UserProfileForm

    def get_context_data(self, **kwargs):
        context = super(TrainerProfileUpdate, self).get_context_data(**kwargs)
        context['my_city'] = self.object.city
        context['user_form'] = self.user_form(instance=self.object.user)
        # ntype 1 is gym to trainer
        context['invites'] = Notification.objects.filter(
            trainer=self.object, ntype=1)
        return context

    def get_object(self):
        return Trainer.objects.get(user=self.request.user)

    def form_valid(self, form):
        if 'cancel' in self.request.POST:
            return redirect('trainer:detail', pk=pk)
        if self.request.POST.get('city', None):
            form.instance.city = get_or_none(City, pk=self.request.POST.get('city'))
        form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse(self.success_url)


@login_required
def photo_save(request):
    if request.user.trainer.photos.count() >= 5:
        return HttpResponse(_('Max is 5'))
    avatar = get_or_none(
        TrainerPhoto, trainer=request.user.trainer, avatar=True)
    photo = TrainerPhoto(
        trainer=request.user.trainer, photo=request.FILES['file'])
    if not avatar:
        photo.avatar = True
    photo.save()
    return HttpResponse('Uploaded')


@login_required
def photo_delete(request, pk):
    photo = get_or_none(Photo, trainer=request.user.trainer, pk=pk)
    if photo:
        photo.delete()
        return HttpResponse('Deleted')
    return HttpResponse('Photo does not exist')

production_static/templates/trainer/detail.html
{% extends "base.html" %}
{% load help_tags %}
{% load socialaccount %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<script src="https://apis.google.com/js/platform.js" async defer></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_PI/sdk.js#xfbml=1&version=v2.6&appId=1714741482131110";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	<div class="center aligned row">
		<div class="column">
			<div class="ui huge star rating" data-rating="{{ rating }}" data-max-rating="5"></div>
		</div>
	</div>
	<div class="right aligned row">
		<div class="column">
			<div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button" data-mobile-iframe="true"></div><div class="g-plus" data-action="share" data-annotation="none" data-height="24"></div>
		</div>
	</div>

	<div class="center aligned row">
		<div class="six wide column">
			<div class="fotorama"
				data-width="300"
				data-height="250"
				data-nav="thumbs"
			>
			{% for photo in object.photos.all %}
				<img src="{{ photo.photo.url }}">
			{% empty %}
				<img src="{% static "image/not_found.png" %}">
			{% endfor %}
			</div>
		</div>
		<div class="four wide column">
			{% get_social_accounts object.user as accounts %}
			{% if accounts.facebook %}
				<a href="{{ accounts.facebook.0.extra_data.link }}" target="_blank" class="ui blue header">Facebook</a>
			{% endif %}
			<p><h4 class="ui header">{{ object.first_name }} {{ object.last_name }}</h4></p>
			{% if object.country %}
				<p><h4 class="ui header">{{ object.country }}, {{ object.city }}</h4></p>
			{% endif %}
			{% if object.phone %}
				<p><h4 class="ui header">{{ object.phone }}</h4></p>
			{% endif %}
			<p><h4 class="ui header">{{ object.user.email }}</h4></p>
		</div>
	</div>
	
	{% if invite %}
	<div class="center aligned row">
		<div class="column">
			<a href="{% url "invite:invite" request.user.gym.pk object.pk 1 %}" class="ui green button active" id="invite">
				Invite trainer
			</a>
		</div>
	</div>
	{% endif %}
	
	<div class="row">
	{% with pk=object.id %}
		{% with form=review_form %}
		<div class="eight wide column parent">
			{% include "review/create.html" %}
		</div>
		{% endwith %}
		{% with form=message_form %}
		<div class="eight wide column">
			{% include "message/create.html" %}
		</div>
		{% endwith %}
	{% endwith %}
	</div>

	<div class="row">
		<div class="column">
				<div class="ui relaxed divided list" id="reviews">
				{% for review in object.reviews.all %}
					<div class="item">
						<div class="right floated content">
							<div class="ui header"> {{ review.get_rate_display }} </div>
						</div>
						<div class="content">
							<div class="header">{{ review.first_name }} {{ review.last_name }}</div>
							<div class="description">{{ review.description }}</div>
							<div class="meta">{{ review.created }}</div>
						</div>
					</div>
				{% empty %}
					<h3 class="ui header">{% trans "Don't have yet" %}</h3>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

production_static/templates/trainer/register.html
{% extends "base.html" %}
{% load socialaccount %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
	<div class="row">
		<div class="column">
			<h2 class="ui centered header">{% trans "Trainers Register" %}</h2>
			<h4 class="ui header green centered">** {% trans "All fields are required" %} **</h4>
			{{ form.errors }}
		</div>
	</div>

	<div class="row">
		<div class="column">
			<form action="" method="post" class="ui form">
			{% csrf_token %}
				<div class="two fields">
					<div class="required field {% if form.first_name.errors %} error {% endif %}">
						<label>{{ form.first_name.label }}:</label>
						{{ form.first_name }}
					</div>
					<div class="required field {% if form.last_name.errors %} error {% endif %}">
						<label>{{ form.last_name.label }}:</label>
						{{ form.last_name }}
					</div>
				</div>
				<div class="required field {% if form.phone.errors %} error {% endif %}">
					<label>{{ form.phone.label }}:</label>
					{{ form.phone }}
				</div>
				<div class="two fields">
					<div class="required field {% if form.country.errors %} error {% endif %}">
						<label>{{ form.country.label }}:</label>
						{{ form.country }}
					</div>
					<div class="required field {% if form.city.errors %} error {% endif %}">
						<label>City:</label>
						<select id="id_city" name="city">
							<option value="">{% trans "Please, select the country" %}...</option>
						</select>
					</div>
				</div>
				<div class="field">
					<button type="submit" class="ui blue button">{% trans "Register" %}</button>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

production_static/templates/trainer/settings.html
{% extends "base.html" %}
{% load socialaccount %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
	<div class="row">
		<div class="column">
			<h3 class="ui blue centered header">{% trans "Please, fill your profile." %}</h3>
		</div>
	</div>

	<div class="row">
		<div class="column">
			<div class="ui tabular menu">
				<a class="active item" data-tab="details">{% trans "Details" %}</a>
				<a class="item" data-tab="photos">{% trans "Photos" %}</a>
				<a class="item" data-tab="gyms">{% trans "Gyms" %}</a>
				<a class="item" data-tab="user">{% trans "User details" %}</a>
				<a class="item" data-tab="payments">{% trans "Payments" %}</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="column">
			<div class="ui active tab" data-tab="details">
				{% include "trainer/settings/details.html" %}
			</div>
			<div class="ui tab" data-tab="photos">
				{% include "trainer/settings/photos.html" %}
			</div>
			<div class="ui tab" data-tab="gyms">
				{% include "trainer/settings/gyms.html" %}
			</div>
			<div class="ui tab" data-tab="user">
				{% include "support/settings/user_details.html" %}
			</div>
			<div class="ui tab" data-tab="payments">
				{% include "support/settings/payments.html" %}
			</div>
		</div>
	</div>
{% endblock %}